CRJ-Shop1-Testinlämning/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CRJ_Shop.Data;
using CRJ_Shop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace CRJ_Shop.Pages
{
    public class CartModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public CartModel(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public AppUser? AppUser { get; set; }
        public List<CartItem> CartItem { get; set; }
        public bool SuccessMessage { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (User is null)
            {
                return RedirectToPage("/Account/Login");
            }

            CartItem = await _context.CartItems
                .Include(c => c.Product)
                .ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveFromCart(int itemId)
        {
            var cartItem = await _context.CartItems.FindAsync(itemId);
            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddToCart(int productId)
        {
            AppUser = await _userManager.GetUserAsync(User);

            if (AppUser is null)
            {
                return RedirectToPage("/Account/Login");
            }

            var cartItem = await _context.CartItems.FirstOrDefaultAsync(m => m.ProductId == productId);
            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == productId);


            if (cartItem == null)
            {
                cartItem = new CartItem()
                {
                    ProductId = productId,
                    Quantity = 1,
                    Product = product,
                    User = AppUser,
                    UserId = AppUser.Id
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity++;
            }

            TempData["AddedProductId"] = productId;
            await _context.SaveChangesAsync();
            return RedirectToPage("/Cart");
        }
    }
}

CRJ-Shop1-Testinlämning/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRJ_Shop.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CRJ-Shop1-Testinlämning/Pages/Index.cshtml.cs
using CRJ_Shop.Data;
using CRJ_Shop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CRJ_Shop.Pages;

public class IndexModel : PageModel
{
    private readonly UserManager<AppUser> _userManager;
    private readonly IUserStore<AppUser> _userStore;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly AppDbContext dbContext;



    public List<Product> ProductList { get; set; }
    public List<Category> Categories { get; set; }
    public string SearchQuery { get; set; }
    public int? SelectedCategoryId { get; set; }
    // Konstruktor
    public IndexModel(
            AppDbContext dbContext,
            UserManager<AppUser> userManager,
            IUserStore<AppUser> userStore,
            RoleManager<IdentityRole> roleManager)
    {
        this.dbContext = dbContext;
        _userManager = userManager;
        _userStore = userStore;
        _roleManager = roleManager;


    }

    public async Task OnGet(string searchQuery, int? selectedCategoryId)
    {
        Categories = await dbContext.Categories.ToListAsync();

        // Show prodcts based on what you search for, and what category you select
        var productsQuery = dbContext.Products.AsQueryable();

        if (!string.IsNullOrEmpty(searchQuery))
        {
            productsQuery = productsQuery.Where(p => p.Name.Contains(searchQuery));
            SearchQuery = searchQuery;
        }

        // Category filter
        if (selectedCategoryId.HasValue)
        {
            var selectedCategory = await dbContext.Categories
                .FirstOrDefaultAsync(c => c.Id == selectedCategoryId);

            if (selectedCategory != null)
            {
                productsQuery = productsQuery.Where(p => p.ProductCategories
                    .Any(pc => pc.Category.ProductCategory == selectedCategory.ProductCategory));
                SelectedCategoryId = selectedCategoryId; // Persist the selected category ID
            }
        }

        // Fetch the filtered product list
        ProductList = await productsQuery.ToListAsync();
    }



}

CRJ-Shop1-Testinlämning/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRJ_Shop.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

CRJ-Shop1-Testinlämning/Pages/Cart.cshtml
@page
@model CRJ_Shop.Pages.CartModel
@{
}

<div class="container my-5">
    <h2>Your Cart</h2>
    @if (Model.CartItem != null && Model.CartItem.Count > 0)
    {
        <table class="table mb-5">
            <thead>
            <tr class="h6">
                <th>Product</th>
                <th>Quantity</th>
                <th>Price per</th>
                <th>Tot Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.CartItem)
            {
                <tr>
                    <td class="">@item.Product?.Name</td>
                    <td class="font-monospace">x @item.Quantity</td>
                    <td class="font-monospace">@item.Product!.Price:-</td>
                    @if (item.Quantity < 1)
                    {
                        <td class="font-monospace">@item.Product.Price:-</td>
                    }
                    else
                    {
                        <td class="font-monospace">@(item.Product.Price * item.Quantity):-</td>
                    }

                    <td>
                        <form method="post" asp-page-handler="RemoveFromCart" class="d-flex justify-content-end">
                            <input type="hidden" name="itemId" value="@item.Id"/>
                            <button type="submit" class="text-danger border-0 fw-bold bg-transparent rounded-pill">Remove</button>
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <div class="d-flex justify-content-end flex-column gap-2">
            <span class="d-flex justify-content-end fw-bold h4 font-monospace">
                Total: @Model.CartItem.Sum(x => x.Product.Price * x.Quantity) SEK
            </span>
            <div class="d-flex justify-content-end">
                <a asp-page="Orders/Preview" class="d-flex btn btn-success"> Go to checkout</a>
            </div>

            <a href='javascript:history.go(-1)' class="mb-5">&#10094; Continue shopping</a>
        </div>
    }
    else
    {
        <p>Your cart is empty.</p>
        <a href="/products" class="mb-5">&#10094; Continue shopping</a>
    }
</div>

CRJ-Shop1-Testinlämning/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="my-5">
    <form method="get" class="d-flex justify-content-between  w-100 my-4 gap-2">
        <div class="d-flex justify-content-between w-100 gap-2">
            <select class="form-select w-25" id="selectedCategoryId"
                    name="selectedCategoryId"
                    onchange="this.form.submit()">
                <option value="">All Categories</option>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.Id" selected="@(category.Id == Model.SelectedCategoryId ? "selected" : null)">
                        @category.ProductCategory
                    </option>
                }
            </select>
            <input type="text"
                   placeholder="Search"
                   class="form-control"
                   id="searchQuery"
                   name="searchQuery"
                   value="@Model.SearchQuery"
                   onchange="this.form.submit()" />
        </div>
    </form>

    <div class="row">
        @foreach(var product in Model.ProductList)
        {
            <div class="col-sm-6 col-md-4 col-lg-3 mb-2">
                <div class="card h-100 pb-2">
                    <a asp-page="/products/product" asp-route-id="@product.Id" class="card-body text-black text-decoration-none">
                        <img src="@(!string.IsNullOrEmpty(product.Image) ? product.Image : "https://placehold.co/600x400")" class="w-100 mb-2" alt="Example image" />
                        <h4 class="fw-bold h6">@product.Name</h4>
                        <div class="text-truncate">@product.Description</div>
                    </a>

                    <div class="px-3 d-flex justify-content-between align-items-center">

                        <form method="post" asp-page="/cart" asp-page-handler="AddToCart">
                            <input type="hidden" name="productId" value="@product.Id" />
                            <button type="submit" class="d-flex justify-content-center gap-2 btn btn-outline-dark py-1 h6 px-2 rounded-3 mt-1 mb-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                                    <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9z" />
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
                                </svg>
                                Add to cart
                            </button>
                        </form>

                        <span class="h5 fw-bold font-monospace">@product.Price SEK</span>

                    </div>


                </div>
            </div>
        }
    </div>

</div>